### PR TITLE
fix: don't convert header names to lowercase

### LINKED ISSUE #74: Don't convert header names to lowercase
This is a super minor issue of aesthetics, but since HTTP header names are case insensitive, it would be nice if the header names are preserved as provided in the HAR object. I just think it looks nicer in my documentation to have:

```
-H 'Authorization: Bearer <Your Token>'
```

Instead of:

```
-H 'authorization: Bearer <Your Token>'
```

### PR DESCRIPTION
**Pull request by jgiovaresco**
I've completed @darrenjennings branch to remove the `.toLowerCase` for header names.

Closes #74

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -75,7 +75,7 @@ HTTPSnippet.prototype.prepare = function (request) {
   if (request.headers && request.headers.length) {
     // loweCase header keys
     request.headersObj = request.headers.reduce(function (headers, header) {
-      headers[header.name.toLowerCase()] = header.value
+      headers[header.name] = header.value
```
Comment (develohpanda) [inline src/index.js]: There is a comment in the linked issue mentioning that HTTP/2 _requires_ headers to be lowercase, while they are case-insensitive in HTTP/1.1 - https://github.com/Kong/httpsnippet/issues/74#issuecomment-561412157.

That's a great point, and since we have access to the version here (`request.httpVersion`) I am inclined suggest only converting to lowercase with HTTP/2, and use `header.name` as-is with other cases.

**Review by develohpanda — COMMENTED** [review]
Thanks for finishing this off!

Do you have any thoughts about whether handling headers with HTTP/1.1 (case-insensitive) vs HTTP/2 (case-sensitive) is the responsibility of this library, or responsibility of the consumer? (cc: @darrenjennings)

I am impartial, but since we have access to the version on the HAR object, we might as well follow the [RFC](https://tools.ietf.org/html/rfc7540#section-8.1.2).

File: src/index.js (hunk 1 above)
Comment (darrenjennings) [reply src/index.js]: Makes sense to me. @jgiovaresco can you add `httpVersion` detection and only lowercase on http/2.x?

re:
> Malformed Requests and Responses
A malformed request or response is one that is an otherwise valid
sequence of HTTP/2 frames but is invalid due to the presence of
extraneous frames, prohibited header fields, the absence of mandatory
header fields, or the inclusion of uppercase header field names.

File: src/index.js [hunk 2]
```diff
@@ -75,7 +75,12 @@ HTTPSnippet.prototype.prepare = function (request) {
   if (request.headers && request.headers.length) {
     // loweCase header keys
     request.headersObj = request.headers.reduce(function (headers, header) {
-      headers[header.name.toLowerCase()] = header.value
+      var headerName = header.name
+      if (request.httpVersion.match(/^HTTP\/2/)) {
```
Comment (develohpanda) [inline src/index.js]: As a performance bump, it would be good to declare this regex once and re-use it rather than constructing it within each iteration of `.reduce()` 😄

**Review by develohpanda — CHANGES_REQUESTED** [review]
Looks good now, nice to see an additional unit test! 👍

Just a minor comment on the use of regex

**Review by develohpanda — APPROVED** [review]
Nicely done 🙌

**Comment by reynolek** [comment]
released in 1.23.0

**Comment by erunion** [comment]
This change has unfortunately introduced some header duping in some cases of commonly used headers like `Content-Type` where if it's as `Content-Type` in the HAR, but a target is looking for `content-type` or adds its own `content-type` header (like in `multipart/form-data` where it is overridden) we end up with double headers containing potentially differing values.

I'm working on a PR right now though.
